version: '3'
services:
  highland-workshop:
    build: .
    environment:
      - MODE=production
      - HOST=database
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    image: mongo:latest